version: "3"
services:
  ipsec-server:
    container_name: ipsec-server
    image: hwdsl2/ipsec-vpn-server
    privileged: true
    env_file: ./vpn.env
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - /lib/modules:/lib/modules:ro