version: "3"
services:
  ss-server:
    container_name: ss-server
    image: willmao/shadowsocks
    ports:
      - "6500:6500"
    entrypoint: ss-server -s 0.0.0.0 -p 6500 -m aes-256-cfb -k abc123_ --fast-open

  ss-client:
    container_name: ss-client
    image: willmao/shadowsocks
    restart: always
    ports:
      - "1080:1080"
    entrypoint: ss-local -s 0.0.0.0 -p 6500 -b 127.0.0.1 -l 1080 -m aes-256-cfb -k abc123_ --fast-open
